# Dataframes

In [1]:
import numpy as np
import pandas as pd

###  Creating DataFrame

In [2]:

# using lists 
student_data = [
    [105, 85, 6.5],
    [130, 92, 18.0],
    [98, 75, 4.2],
    [115, 88, 11.5]
]



pd.DataFrame(student_data , columns=['iq','marks', 'package'])

    iq  marks  package
0  105     85      6.5
1  130     92     18.0
2   98     75      4.2
3  115     88     11.5

In [3]:
# using dict 
student = {
    'iq':[100,120,230,300,120],
    'marks':[89,56,99,100,30],
    'package':[10,30,20,12,34]
}

student = pd.DataFrame(student)

In [4]:
#using read_csv
titanic = pd.read_csv("titanic.csv")107.0 K107.0 KB107.0 KB107.0 KBB

In [5]:
ipl = pd.read_csv('ipl.csv')

## DataFrame Attributes and methods

In [6]:
# shape
ipl.shape

(577, 18)

In [7]:
# dtypes
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [8]:
# index
ipl.index

RangeIndex(start=0, stop=577, step=1)

In [9]:
# columns 
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [10]:
# values
student.values

array([[100,  89,  10],
       [120,  56,  30],
       [230,  99,  20],
       [300, 100,  12],
       [120,  30,  34]])

In [11]:
# head and tail
ipl.head(3)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2008,Bangalore,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
1,2,2008,Chandigarh,2008-04-19,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Chennai Super Kings,33,0,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",MR Benson,SL Shastri,NaN
2,3,2008,Delhi,2008-04-19,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals,bat,normal,0,Delhi Daredevils,0,9,MF Maharoof,Feroz Shah Kotla,Aleem Dar,GA Pratapkumar,NaN

In [12]:
titanic.tail(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [13]:
# sample 
ipl.sample(3)  # random row

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
251,252,2012,Jaipur,2012-04-06,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,normal,0,Rajasthan Royals,31,0,AM Rahane,Sawai Mansingh Stadium,BF Bowden,SK Tarapore,NaN
339,340,2013,Chennai,2013-04-15,Pune Warriors,Chennai Super Kings,Pune Warriors,bat,normal,0,Pune Warriors,24,0,SPD Smith,"MA Chidambaram Stadium, Chepauk",Asad Rauf,AK Chaudhary,NaN
17,18,2008,Hyderabad,2008-05-01,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,7,SE Marsh,"Rajiv Gandhi International Stadium, Uppal",BR Doctrove,RB Tiffin,NaN

In [14]:
# info 
ipl.info()

<class 'pandas.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               577 non-null    int64
 1   season           577 non-null    int64
 2   city             570 non-null    str
 3   date             577 non-null    str
 4   team1            577 non-null    str
 5   team2            577 non-null    str
 6   toss_winner      577 non-null    str
 7   toss_decision    577 non-null    str
 8   result           577 non-null    str
 9   dl_applied       577 non-null    int64
 10  winner           574 non-null    str
 11  win_by_runs      577 non-null    int64
 12  win_by_wickets   577 non-null    int64
 13  player_of_match  574 non-null    str
 14  venue            577 non-null    str
 15  umpire1          577 non-null    str
 16  umpire2          577 non-null    str
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), str(12)
memory usage: 168.1 KB

In [15]:
# describe
ipl.describe()  # apply basic maths on all numberic columns

,id,season,dl_applied,win_by_runs,win_by_wickets,umpire3
count,577.000000,577.000000,577.000000,577.000000,577.000000,0.0
mean,289.000000,2012.029463,0.025997,13.715771,3.363951,NaN
std,166.709828,2.486247,0.159263,23.619282,3.416049,NaN
min,1.000000,2008.000000,0.000000,0.000000,0.000000,NaN
25%,145.000000,2010.000000,0.000000,0.000000,0.000000,NaN
50%,289.000000,2012.000000,0.000000,0.000000,3.000000,NaN
75%,433.000000,2014.000000,0.000000,20.000000,6.000000,NaN
max,577.000000,2016.000000,1.000000,144.000000,10.000000,NaN

In [16]:
# isnull
ipl.isnull()
ipl.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               3
win_by_runs          0
win_by_wickets       0
player_of_match      3
venue                0
umpire1              0
umpire2              0
umpire3            577
dtype: int64

In [17]:
# duplicated 
ipl.duplicated()

ipl.duplicated().sum()

np.int64(0)

In [18]:
# rename 
student.rename(columns={'marks':'percentage','package':'LPA'})

    iq  percentage  LPA
0  100          89   10
1  120          56   30
2  230          99   20
3  300         100   12
4  120          30   34

## Math methods

In [21]:
titanic.sum()
student.sum(axis=1)  # row wise

0    199
1    206
2    349
3    412
4    184
dtype: int64

In [22]:
student.min()

iq         100
marks       30
package     10
dtype: int64

In [23]:
student.median()

iq         120.0
marks       89.0
package     20.0
dtype: float64

In [24]:
student.std()

iq         87.063195
marks      30.752236
package    10.639549
dtype: float64

In [25]:
student.var()   # variance

iq         7580.0
marks       945.7
package     113.2
dtype: float64

## Selecting cols from a dataframe

In [28]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [34]:
# single cols
titanic['Pclass']

0      3
1      3
2      2
3      3
4      3
      ..
413    3
414    1
415    3
416    3
417    3
Name: Pclass, Length: 418, dtype: int64

In [40]:
# multiple cols
titanic[['PassengerId','Sex','Survived']]

     PassengerId     Sex  Survived
0            892    male         0
1            893  female         1
2            894    male         0
3            895    male         0
4            896  female         1
..           ...     ...       ...
413         1305    male         0
414         1306  female         1
415         1307    male         0
416         1308    male         0
417         1309    male         0

[418 rows x 3 columns]

### SelectSelecting row from a Dataframe

In [65]:
# inserting new col
# student.insert(0,"name", ["Rahul",'Vijay','Dinesh','kiran','Druva'])

In [67]:
# student.set_index('name',inplace=True)
student

         iq  marks  package
name
Rahul   100     89       10
Vijay   120     56       30
Dinesh  230     99       20
kiran   300    100       12
Druva   120     30       34

In [71]:
# single row 
student.iloc[0]

iq         100
marks       89
package     10
Name: Rahul, dtype: int64

In [73]:
# multiple rows
student.iloc[0:4:2]

         iq  marks  package
name
Rahul   100     89       10
Dinesh  230     99       20

In [75]:
# loc locating using label
student.loc['Rahul':'Dinesh']

         iq  marks  package
name
Rahul   100     89       10
Vijay   120     56       30
Dinesh  230     99       20

### Selecting both rows and cols

In [76]:
student.iloc[0:2,0:2]

        iq  marks
name
Rahul  100     89
Vijay  120     56

### Filtering a dataframe

In [86]:
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2008,Bangalore,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
1,2,2008,Chandigarh,2008-04-19,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Chennai Super Kings,33,0,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",MR Benson,SL Shastri,NaN
2,3,2008,Delhi,2008-04-19,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals,bat,normal,0,Delhi Daredevils,0,9,MF Maharoof,Feroz Shah Kotla,Aleem Dar,GA Pratapkumar,NaN
3,4,2008,Mumbai,2008-04-20,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,normal,0,Royal Challengers Bangalore,0,5,MV Boucher,Wankhede Stadium,SJ Davis,DJ Harper,NaN
4,5,2008,Kolkata,2008-04-20,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,bat,normal,0,Kolkata Knight Riders,0,5,DJ Hussey,Eden Gardens,BF Bowden,K Hariharan,NaN

In [93]:
# how many matched have dl applied
ipl[ipl['dl_applied']!=0].shape[0]

15

In [101]:
# how many match csk won in Eden Gardens
csk = ipl[(ipl['winner']=='Chennai Super Kings') & (ipl['venue']=='Eden Gardens')]
csk

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
43,44,2008,Kolkata,2008-05-18,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,bat,normal,1,Chennai Super Kings,3,0,M Ntini,Eden Gardens,Asad Rauf,K Hariharan,NaN
122,123,2010,Kolkata,2010-03-16,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,bat,normal,0,Chennai Super Kings,55,0,MS Dhoni,Eden Gardens,HDPK Dharmasena,AM Saheba,NaN
308,309,2012,Kolkata,2012-05-14,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,5,MEK Hussey,Eden Gardens,JD Cloete,SJA Taufel,NaN
346,347,2013,Kolkata,2013-04-20,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,bat,normal,0,Chennai Super Kings,0,4,RA Jadeja,Eden Gardens,Asad Rauf,AK Chaudhary,NaN

In [121]:
# toss winner is match winner in percentage
tosswin = ipl[ipl['toss_winner']==ipl['winner']]
(tosswin.shape[0]/ipl.shape[0])*100

50.43327556325823

In [124]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [135]:
# how many people of pcalss 2 survived
titanic[(titanic['Pclass'] == 2) & (titanic['Survived']== 1)].shape[0]

30

In [141]:
# apply
titanic['Age'].apply(lambda x: x + 1)

0      37.5
1      50.0
2      65.0
3      30.0
4      25.0
       ...
413     NaN
414    42.0
415    41.5
416     NaN
417     NaN
Name: Age, Length: 418, dtype: float64

In [148]:
# contains()
titanic[titanic['Name'].str.contains('James.', na=False)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,49.0,1,0,363272,7.0000,NaN,S
180,1072,0,2,"McCrie, Mr. James Matthew",male,32.0,0,0,233478,13.0000,NaN,S
229,1121,0,2,"Hocking, Mr. Samuel James Metcalfe",male,38.0,0,0,242963,13.0000,NaN,S
247,1139,0,2,"Drew, Mr. James Vivian",male,44.0,1,1,28220,32.5000,NaN,S
343,1235,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,60.0,0,1,PC 17755,512.3292,B51 B53 B55,C
344,1236,0,3,"van Billiard, Master. James William",male,NaN,1,1,A/5. 851,14.5000,NaN,S
362,1254,1,2,"Ware, Mrs. John James (Florence Louise Long)",female,33.0,0,0,CA 31352,21.0000,NaN,S
391,1283,1,1,"Lines, Mrs. Ernest H (Elizabeth Lindsey James)",female,53.0,0,1,PC 17592,39.4000,D28,S

### Adding new cols

In [153]:
# student['Pass']= 'India' 
# creates new column of pass

In [152]:
student

         iq  marks  package   Pass
name
Rahul   100     89       10  India
Vijay   120     56       30  India
Dinesh  230     99       20  India
kiran   300    100       12  India
Druva   120     30       34  India

In [156]:
# from existing ones 
titanic.dropna(inplace=True)
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,25.0,1,0,21228,82.2667,B45,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,49.0,1,0,W.E.P. 5734,61.1750,E31,S
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,50.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
26,918,1,1,"Ostby, Miss. Helene Ragnhild",female,24.0,0,1,113509,61.9792,B36,C
28,920,0,1,"Brady, Mr. John Bertram",male,43.0,0,0,113054,30.5000,A21,S
...,...,...,...,...,...,...,...,...,...,...,...,...
404,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,45.0,1,0,17765,27.7208,D40,C
405,1297,0,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,22.0,0,0,SC/PARIS 2166,13.8625,D38,C
407,1299,0,1,"Widener, Mr. George Dunton",male,52.0,1,1,113503,211.5000,C80,C
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,39.0,1,0,19928,90.0000,C78,Q
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,41.0,0,0,PC 17758,108.9000,C105,C

In [159]:
titanic["Cabin_series"] = titanic['Cabin'].apply(lambda x:x[0])
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Cabin_series
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,25.0,1,0,21228,82.2667,B45,S,B
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,49.0,1,0,W.E.P. 5734,61.1750,E31,S,E
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,50.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C,B
26,918,1,1,"Ostby, Miss. Helene Ragnhild",female,24.0,0,1,113509,61.9792,B36,C,B
28,920,0,1,"Brady, Mr. John Bertram",male,43.0,0,0,113054,30.5000,A21,S,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,45.0,1,0,17765,27.7208,D40,C,D
405,1297,0,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,22.0,0,0,SC/PARIS 2166,13.8625,D38,C,D
407,1299,0,1,"Widener, Mr. George Dunton",male,52.0,1,1,113503,211.5000,C80,C,C
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,39.0,1,0,19928,90.0000,C78,Q,C
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,41.0,0,0,PC 17758,108.9000,C105,C,C

###  Important DataFrame Functions

In [161]:
# astype
ipl.info()  # initially 168.1KB

<class 'pandas.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               577 non-null    int64
 1   season           577 non-null    int64
 2   city             570 non-null    str
 3   date             577 non-null    str
 4   team1            577 non-null    str
 5   team2            577 non-null    str
 6   toss_winner      577 non-null    str
 7   toss_decision    577 non-null    str
 8   result           577 non-null    str
 9   dl_applied       577 non-null    int64
 10  winner           574 non-null    str
 11  win_by_runs      577 non-null    int64
 12  win_by_wickets   577 non-null    int64
 13  player_of_match  574 non-null    str
 14  venue            577 non-null    str
 15  umpire1          577 non-null    str
 16  umpire2          577 non-null    str
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), str(12)
memory usage: 168.1 KB

In [167]:
ipl['season'] = ipl['season'].astype("int16")
ipl.info()  # later 164.7KB

<class 'pandas.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               577 non-null    int64
 1   season           577 non-null    int16
 2   city             570 non-null    str
 3   date             577 non-null    str
 4   team1            577 non-null    str
 5   team2            577 non-null    str
 6   toss_winner      577 non-null    str
 7   toss_decision    577 non-null    str
 8   result           577 non-null    str
 9   dl_applied       577 non-null    int64
 10  winner           574 non-null    str
 11  win_by_runs      577 non-null    int64
 12  win_by_wickets   577 non-null    int64
 13  player_of_match  574 non-null    str
 14  venue            577 non-null    str
 15  umpire1          577 non-null    str
 16  umpire2          577 non-null    str
 17  umpire3          0 non-null      float64
dtypes: float64(1), int16(1), int64(4), str(12)
memory usage: 164.7 KB

In [172]:
# by converting repeated values into categorical data
ipl['toss_decision'] = ipl['toss_decision'].astype("category")
ipl['team1'] = ipl['team1'].astype("category")
ipl['team2'] = ipl['team2'].astype("category")
ipl['result'] = ipl['result'].astype("category")
ipl['venue'] = ipl['venue'].astype("category")
ipl.info() # now 107.0 KB

<class 'pandas.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               577 non-null    int64
 1   season           577 non-null    int16
 2   city             570 non-null    str
 3   date             577 non-null    str
 4   team1            577 non-null    category
 5   team2            577 non-null    category
 6   toss_winner      577 non-null    str
 7   toss_decision    577 non-null    category
 8   result           577 non-null    category
 9   dl_applied       577 non-null    int64
 10  winner           574 non-null    str
 11  win_by_runs      577 non-null    int64
 12  win_by_wickets   577 non-null    int64
 13  player_of_match  574 non-null    str
 14  venue            577 non-null    category
 15  umpire1          577 non-null    str
 16  umpire2          577 non-null    str
 17  umpire3          0 non-null      float64
dtypes: category(5), float64(1), int16(1), int64(4), str(7)
memory usage: 107.0 KB