## 1. Importing Pandas

In [1]:
import pandas as pd

## 2. Opening a local csv file

In [2]:
df = pd.read_csv("eurusd_hour.csv")

In [3]:
df

,Date,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
0,2005-05-02,00:00,1.28520,1.28520,1.28400,1.28440,-0.00080,1.28540,1.28540,1.28420,1.28460,-0.00080
1,2005-05-02,01:00,1.28440,1.28480,1.28390,1.28420,-0.00020,1.28460,1.28500,1.28410,1.28440,-0.00020
2,2005-05-02,02:00,1.28430,1.28540,1.28410,1.28510,0.00080,1.28450,1.28560,1.28430,1.28530,0.00080
3,2005-05-02,03:00,1.28510,1.28590,1.28500,1.28510,0.00000,1.28530,1.28610,1.28520,1.28530,0.00000
4,2005-05-02,04:00,1.28520,1.28590,1.28490,1.28550,0.00030,1.28540,1.28610,1.28510,1.28570,0.00030
...,...,...,...,...,...,...,...,...,...,...,...,...
93079,2020-04-29,18:00,1.08620,1.08851,1.08611,1.08713,0.00093,1.08660,1.08865,1.08640,1.08726,0.00066
93080,2020-04-29,19:00,1.08711,1.08823,1.08659,1.08748,0.00037,1.08725,1.08837,1.08675,1.08760,0.00035
93081,2020-04-29,20:00,1.08747,1.08788,1.08691,1.08708,-0.00039,1.08758,1.08810,1.08706,1.08808,0.00050
93082,2020-04-29,21:00,1.08708,1.08740,1.08699,1.08714,0.00006,1.08808,1.08814,1.08763,1.08766,-0.00042
93083,2020-04-29,22:00,1.08728,1.08760,1.08727,1.08743,0.00015,1.08756,1.08779,1.08749,1.08760,0.00004

## 3 Opening a csv file from an url

In [12]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv" #paste url where u need to get csv file
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}  # keep hearder same 

req = requests.get(url, headers=headers)
data = StringIO(req.text)
df = pd.read_csv(data)
df.head(-20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S

## 4 sep parameter

In [18]:
pd.read_csv("eurusd_hour.csv", sep=",") # when the separaters are currupted and mention the need tab or , 
pd.read_csv("eurusd_hour.csv", sep=",", names=["Date", "Time ","BO","BH" ,"BL", 'BC',"BCh" ,'AO ','AH' ,'AL' ,'AC' ,'ACh'],  low_memory=False)
# USING names to addres the colmun if heading get misplacced

,Date,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
0,Date,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
1,2005-05-02,00:00,1.2852,1.2852,1.284,1.2844,-0.0007999999999999119,1.2854,1.2854,1.2842,1.2846,-0.0008000000000001339
2,2005-05-02,01:00,1.2844,1.2848,1.2839,1.2842,-0.000199999999999978,1.2846,1.285,1.2841,1.2844,-0.000199999999999978
3,2005-05-02,02:00,1.2843,1.2854,1.2841,1.2851,0.0007999999999999119,1.2845,1.2856,1.2843,1.2853,0.0008000000000001339
4,2005-05-02,03:00,1.2851,1.2859,1.285,1.2851,0.0,1.2853,1.2861,1.2852,1.2853,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
93080,2020-04-29,18:00,1.0862,1.08851,1.08611,1.08713,0.0009299999999998754,1.0866,1.08865,1.0864,1.08726,0.000660000000000105
93081,2020-04-29,19:00,1.08711,1.08823,1.08659,1.08748,0.00036999999999998156,1.08725,1.08837,1.08675,1.0876,0.00034999999999985043
93082,2020-04-29,20:00,1.0874700000000002,1.08788,1.08691,1.0870799999999998,-0.0003900000000003345,1.08758,1.0881,1.08706,1.08808,0.0004999999999999449
93083,2020-04-29,21:00,1.0870799999999998,1.0874,1.08699,1.08714,6.0000000000171034e-05,1.08808,1.08814,1.08763,1.08766,-0.00041999999999986487
93084,2020-04-29,22:00,1.08728,1.0876,1.0872700000000002,1.08743,0.00014999999999987246,1.08756,1.08779,1.08749,1.0876,3.9999999999817966e-05

## 5. Index_col parameter

In [26]:
 pd.read_csv("eurusd_hour.csv" , index_col="BO") # used to spectify if any primary key is need to be index

,Date,Time,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
BO,,,,,,,,,,,
1.28520,2005-05-02,00:00,1.28520,1.28400,1.28440,-0.00080,1.28540,1.28540,1.28420,1.28460,-0.00080
1.28440,2005-05-02,01:00,1.28480,1.28390,1.28420,-0.00020,1.28460,1.28500,1.28410,1.28440,-0.00020
1.28430,2005-05-02,02:00,1.28540,1.28410,1.28510,0.00080,1.28450,1.28560,1.28430,1.28530,0.00080
1.28510,2005-05-02,03:00,1.28590,1.28500,1.28510,0.00000,1.28530,1.28610,1.28520,1.28530,0.00000
1.28520,2005-05-02,04:00,1.28590,1.28490,1.28550,0.00030,1.28540,1.28610,1.28510,1.28570,0.00030
...,...,...,...,...,...,...,...,...,...,...,...
1.08620,2020-04-29,18:00,1.08851,1.08611,1.08713,0.00093,1.08660,1.08865,1.08640,1.08726,0.00066
1.08711,2020-04-29,19:00,1.08823,1.08659,1.08748,0.00037,1.08725,1.08837,1.08675,1.08760,0.00035
1.08747,2020-04-29,20:00,1.08788,1.08691,1.08708,-0.00039,1.08758,1.08810,1.08706,1.08808,0.00050
1.08708,2020-04-29,21:00,1.08740,1.08699,1.08714,0.00006,1.08808,1.08814,1.08763,1.08766,-0.00042
1.08728,2020-04-29,22:00,1.08760,1.08727,1.08743,0.00015,1.08756,1.08779,1.08749,1.08760,0.00004

## 6. Header parameter

In [29]:
pd.read_csv("eurusd_hour.csv", header=0 ) # specifing the row of header in case of any miss reading

,Date,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
0,2005-05-02,00:00,1.28520,1.28520,1.28400,1.28440,-0.00080,1.28540,1.28540,1.28420,1.28460,-0.00080
1,2005-05-02,01:00,1.28440,1.28480,1.28390,1.28420,-0.00020,1.28460,1.28500,1.28410,1.28440,-0.00020
2,2005-05-02,02:00,1.28430,1.28540,1.28410,1.28510,0.00080,1.28450,1.28560,1.28430,1.28530,0.00080
3,2005-05-02,03:00,1.28510,1.28590,1.28500,1.28510,0.00000,1.28530,1.28610,1.28520,1.28530,0.00000
4,2005-05-02,04:00,1.28520,1.28590,1.28490,1.28550,0.00030,1.28540,1.28610,1.28510,1.28570,0.00030
...,...,...,...,...,...,...,...,...,...,...,...,...
93079,2020-04-29,18:00,1.08620,1.08851,1.08611,1.08713,0.00093,1.08660,1.08865,1.08640,1.08726,0.00066
93080,2020-04-29,19:00,1.08711,1.08823,1.08659,1.08748,0.00037,1.08725,1.08837,1.08675,1.08760,0.00035
93081,2020-04-29,20:00,1.08747,1.08788,1.08691,1.08708,-0.00039,1.08758,1.08810,1.08706,1.08808,0.00050
93082,2020-04-29,21:00,1.08708,1.08740,1.08699,1.08714,0.00006,1.08808,1.08814,1.08763,1.08766,-0.00042
93083,2020-04-29,22:00,1.08728,1.08760,1.08727,1.08743,0.00015,1.08756,1.08779,1.08749,1.08760,0.00004

## 7. use_cols parameter

In [33]:
pd.read_csv("eurusd_hour.csv", usecols=["Date", "BO", 'BH'])  # to specify necesary columns which dont read unnecessay columns

             Date       BO       BH
0      2005-05-02  1.28520  1.28520
1      2005-05-02  1.28440  1.28480
2      2005-05-02  1.28430  1.28540
3      2005-05-02  1.28510  1.28590
4      2005-05-02  1.28520  1.28590
...           ...      ...      ...
93079  2020-04-29  1.08620  1.08851
93080  2020-04-29  1.08711  1.08823
93081  2020-04-29  1.08747  1.08788
93082  2020-04-29  1.08708  1.08740
93083  2020-04-29  1.08728  1.08760

[93084 rows x 3 columns]

## 8. skiprows/nrow Parameter

In [38]:
pd.read_csv("eurusd_hour.csv",skiprows=[1,3])
pd.read_csv("eurusd_hour.csv",nrows=100)

,Date,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
0,2005-05-02,00:00,1.2852,1.2852,1.2840,1.2844,-0.0008,1.2854,1.2854,1.2842,1.2846,-0.0008
1,2005-05-02,01:00,1.2844,1.2848,1.2839,1.2842,-0.0002,1.2846,1.2850,1.2841,1.2844,-0.0002
2,2005-05-02,02:00,1.2843,1.2854,1.2841,1.2851,0.0008,1.2845,1.2856,1.2843,1.2853,0.0008
3,2005-05-02,03:00,1.2851,1.2859,1.2850,1.2851,0.0000,1.2853,1.2861,1.2852,1.2853,0.0000
4,2005-05-02,04:00,1.2852,1.2859,1.2849,1.2855,0.0003,1.2854,1.2861,1.2851,1.2857,0.0003
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2005-05-05,23:00,1.2952,1.2953,1.2945,1.2945,-0.0007,1.2954,1.2955,1.2947,1.2947,-0.0007
96,2005-05-06,00:00,1.2945,1.2947,1.2934,1.2944,-0.0001,1.2947,1.2949,1.2936,1.2946,-0.0001
97,2005-05-06,01:00,1.2945,1.2945,1.2938,1.2939,-0.0006,1.2947,1.2947,1.2940,1.2941,-0.0006
98,2005-05-06,02:00,1.2938,1.2946,1.2932,1.2944,0.0006,1.2940,1.2948,1.2934,1.2946,0.0006
99,2005-05-06,03:00,1.2943,1.2945,1.2940,1.2942,-0.0001,1.2945,1.2947,1.2942,1.2944,-0.0001

## 9. Encoding parameter

In [40]:
pd.read_csv("eurusd_hour.csv",encoding="latin-1")  #to interpret the raw bytes in the file as text characters

,Date,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
0,2005-05-02,00:00,1.28520,1.28520,1.28400,1.28440,-0.00080,1.28540,1.28540,1.28420,1.28460,-0.00080
1,2005-05-02,01:00,1.28440,1.28480,1.28390,1.28420,-0.00020,1.28460,1.28500,1.28410,1.28440,-0.00020
2,2005-05-02,02:00,1.28430,1.28540,1.28410,1.28510,0.00080,1.28450,1.28560,1.28430,1.28530,0.00080
3,2005-05-02,03:00,1.28510,1.28590,1.28500,1.28510,0.00000,1.28530,1.28610,1.28520,1.28530,0.00000
4,2005-05-02,04:00,1.28520,1.28590,1.28490,1.28550,0.00030,1.28540,1.28610,1.28510,1.28570,0.00030
...,...,...,...,...,...,...,...,...,...,...,...,...
93079,2020-04-29,18:00,1.08620,1.08851,1.08611,1.08713,0.00093,1.08660,1.08865,1.08640,1.08726,0.00066
93080,2020-04-29,19:00,1.08711,1.08823,1.08659,1.08748,0.00037,1.08725,1.08837,1.08675,1.08760,0.00035
93081,2020-04-29,20:00,1.08747,1.08788,1.08691,1.08708,-0.00039,1.08758,1.08810,1.08706,1.08808,0.00050
93082,2020-04-29,21:00,1.08708,1.08740,1.08699,1.08714,0.00006,1.08808,1.08814,1.08763,1.08766,-0.00042
93083,2020-04-29,22:00,1.08728,1.08760,1.08727,1.08743,0.00015,1.08756,1.08779,1.08749,1.08760,0.00004

In [41]:
## 11 skip bad lines

In [43]:
pd.read_csv("eurusd_hour.csv", on_bad_lines="skip")  #  skips the line which has errors and stop table from getting crashed

,Date,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
0,2005-05-02,00:00,1.28520,1.28520,1.28400,1.28440,-0.00080,1.28540,1.28540,1.28420,1.28460,-0.00080
1,2005-05-02,01:00,1.28440,1.28480,1.28390,1.28420,-0.00020,1.28460,1.28500,1.28410,1.28440,-0.00020
2,2005-05-02,02:00,1.28430,1.28540,1.28410,1.28510,0.00080,1.28450,1.28560,1.28430,1.28530,0.00080
3,2005-05-02,03:00,1.28510,1.28590,1.28500,1.28510,0.00000,1.28530,1.28610,1.28520,1.28530,0.00000
4,2005-05-02,04:00,1.28520,1.28590,1.28490,1.28550,0.00030,1.28540,1.28610,1.28510,1.28570,0.00030
...,...,...,...,...,...,...,...,...,...,...,...,...
93079,2020-04-29,18:00,1.08620,1.08851,1.08611,1.08713,0.00093,1.08660,1.08865,1.08640,1.08726,0.00066
93080,2020-04-29,19:00,1.08711,1.08823,1.08659,1.08748,0.00037,1.08725,1.08837,1.08675,1.08760,0.00035
93081,2020-04-29,20:00,1.08747,1.08788,1.08691,1.08708,-0.00039,1.08758,1.08810,1.08706,1.08808,0.00050
93082,2020-04-29,21:00,1.08708,1.08740,1.08699,1.08714,0.00006,1.08808,1.08814,1.08763,1.08766,-0.00042
93083,2020-04-29,22:00,1.08728,1.08760,1.08727,1.08743,0.00015,1.08756,1.08779,1.08749,1.08760,0.00004

In [44]:
## Handeling date

In [47]:
pd.read_csv("eurusd_hour.csv", parse_dates=["Date"])  # it helps to read date as date not as object(string)

,Date,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
0,2005-05-02,00:00,1.28520,1.28520,1.28400,1.28440,-0.00080,1.28540,1.28540,1.28420,1.28460,-0.00080
1,2005-05-02,01:00,1.28440,1.28480,1.28390,1.28420,-0.00020,1.28460,1.28500,1.28410,1.28440,-0.00020
2,2005-05-02,02:00,1.28430,1.28540,1.28410,1.28510,0.00080,1.28450,1.28560,1.28430,1.28530,0.00080
3,2005-05-02,03:00,1.28510,1.28590,1.28500,1.28510,0.00000,1.28530,1.28610,1.28520,1.28530,0.00000
4,2005-05-02,04:00,1.28520,1.28590,1.28490,1.28550,0.00030,1.28540,1.28610,1.28510,1.28570,0.00030
...,...,...,...,...,...,...,...,...,...,...,...,...
93079,2020-04-29,18:00,1.08620,1.08851,1.08611,1.08713,0.00093,1.08660,1.08865,1.08640,1.08726,0.00066
93080,2020-04-29,19:00,1.08711,1.08823,1.08659,1.08748,0.00037,1.08725,1.08837,1.08675,1.08760,0.00035
93081,2020-04-29,20:00,1.08747,1.08788,1.08691,1.08708,-0.00039,1.08758,1.08810,1.08706,1.08808,0.00050
93082,2020-04-29,21:00,1.08708,1.08740,1.08699,1.08714,0.00006,1.08808,1.08814,1.08763,1.08766,-0.00042
93083,2020-04-29,22:00,1.08728,1.08760,1.08727,1.08743,0.00015,1.08756,1.08779,1.08749,1.08760,0.00004

In [48]:
## converters

In [54]:
def rename(Time):
    if Time == "01:00":
        return "1am"
    else: 
        return Time

In [56]:
pd.read_csv("eurusd_hour.csv", converters={'Time':rename})  #custom function to transform the raw values of a specific column

,Date,Time,BO,BH,BL,BC,BCh,AO,AH,AL,AC,ACh
0,2005-05-02,00:00,1.28520,1.28520,1.28400,1.28440,-0.00080,1.28540,1.28540,1.28420,1.28460,-0.00080
1,2005-05-02,1am,1.28440,1.28480,1.28390,1.28420,-0.00020,1.28460,1.28500,1.28410,1.28440,-0.00020
2,2005-05-02,02:00,1.28430,1.28540,1.28410,1.28510,0.00080,1.28450,1.28560,1.28430,1.28530,0.00080
3,2005-05-02,03:00,1.28510,1.28590,1.28500,1.28510,0.00000,1.28530,1.28610,1.28520,1.28530,0.00000
4,2005-05-02,04:00,1.28520,1.28590,1.28490,1.28550,0.00030,1.28540,1.28610,1.28510,1.28570,0.00030
...,...,...,...,...,...,...,...,...,...,...,...,...
93079,2020-04-29,18:00,1.08620,1.08851,1.08611,1.08713,0.00093,1.08660,1.08865,1.08640,1.08726,0.00066
93080,2020-04-29,19:00,1.08711,1.08823,1.08659,1.08748,0.00037,1.08725,1.08837,1.08675,1.08760,0.00035
93081,2020-04-29,20:00,1.08747,1.08788,1.08691,1.08708,-0.00039,1.08758,1.08810,1.08706,1.08808,0.00050
93082,2020-04-29,21:00,1.08708,1.08740,1.08699,1.08714,0.00006,1.08808,1.08814,1.08763,1.08766,-0.00042
93083,2020-04-29,22:00,1.08728,1.08760,1.08727,1.08743,0.00015,1.08756,1.08779,1.08749,1.08760,0.00004

In [ ]:
## loading a huge dataset in chunks

In [64]:
df = pd.read_csv("eurusd_hour.csv", chunksize=500)